Repository TheAutobanApp/Autoban, pull requests merged in 2020-08, with the labels that each got.

#29 Add Column component
  client/src/App.js
  client/src/components/AddColumn.js
  client/src/components/OptionsDrawer.js
  client/src/styles/style.css
Labels: Front End

#30 25 drawer conditionals
  client/src/App.js
  client/src/AutoContext.js
  client/src/components/Column.js
  client/src/components/DropMenu.js
  client/src/components/Label.js
  client/src/components/Navbar.js
  client/src/components/OptionsDrawer.js
  client/src/components/drawerviews/CardDrawerView.js
  client/src/components/drawerviews/ColumnDrawerView.js
  client/src/components/drawerviews/SettingsDrawerView.js
  package.json
Labels: Front End

#32 View Switch, add column functionality with context, responsive render for column and cards
  client/src/App.js
  client/src/components/AddColumn.js
  client/src/components/Column.js
  client/src/components/DropMenu.js
  client/src/components/Navbar.js
  client/src/components/OptionsDrawer.js
  client/src/components/Timeline.js
  client/src/components/drawerviews/SettingsDrawerView.js
  client/src/styles/style.css
Labels: Front End

#37 35 route configuration
  config/config.json
  controllers/apiRoutes/column.js
  controllers/apiRoutes/index.js
  controllers/apiRoutes/project.js
  controllers/apiRoutes/task.js
  controllers/apiRoutes/user.js
  controllers/index.js
  controllers/localdata/columns.js
  models/Column.js
  models/Label.js
  server.js
Labels: Back End

#40 Column api routes built. Integrated corresponding axios calls on front end. Fixed two errors.
  client/src/App.js
  client/src/components/AddColumn.js
  client/src/components/DropMenu.js
  client/src/components/drawerviews/ColumnDrawerView.js
  client/src/components/drawerviews/SettingsDrawerView.js
  controllers/apiRoutes/column.js
  controllers/apiRoutes/columns.js
  controllers/apiRoutes/index.js
  models/Column.js
Labels: Back End, Front End

#50 Labels added to front end, routes created. Nav drawer updated
  client/src/components/CardComponent.js
  client/src/components/DropMenu.js
  client/src/components/Navbar.js
  client/src/components/TaskModal.js
  client/src/components/TeamDropItem.js
  client/src/components/TeamDropdown.js
  client/src/components/UserDropdown.js
  client/src/styles/style.css
  controllers/apiRoutes/index.js
  controllers/apiRoutes/label.js
  models/Label.js
Labels: Back End, Front End

#52 51 authentication
  client/src/App.js
  client/src/Firebase.js
  client/src/components/Login.js
  client/src/components/UserDropdown.js
  models/User.js
  package.json
Labels: Back End, Front End

#54 User creation
  client/src/App.js
  client/src/components/Login.js
  client/src/components/UserDropdown.js
  client/src/styles/style.css
  config/config.json
  controllers/apiRoutes/user.js
  models/User.js
Labels: Back End, Front End

#56 55 homeview comp
  client/src/App.js
  client/src/components/Homeview.js
  client/src/components/ProjectCard.js
  client/src/components/TeamMenu.js
  client/src/styles/style.css
Labels: Front End

#58 Made labels persistent, updated routes, added label creation functionality with modal and dropdown.
  client/src/App.js
  client/src/components/AddColumn.js
  client/src/components/CardComponent.js
  client/src/components/Column.js
  client/src/components/DropMenu.js
  client/src/components/LabelModal.js
  client/src/components/Navbar.js
  client/src/components/ProjectView.js
  client/src/components/TeamDropItem.js
  client/src/components/TeamMenu.js
  client/src/components/drawerviews/ColumnDrawerView.js
  client/src/styles/style.css
  controllers/apiRoutes/label.js
  controllers/apiRoutes/task.js
Labels: Back End, Front End

#62 61 add project
  client/src/App.js
  client/src/components/AddProject.js
  client/src/components/Homeview.js
  client/src/components/Login.js
  client/src/components/Navbar.js
  client/src/components/TeamMenu.js
  client/src/components/modals/LabelModal.js
  client/src/components/modals/ProjectModal.js
  client/src/components/modals/TaskModal.js
  client/src/styles/style.css
  config/config.json
  controllers/apiRoutes/project.js
  controllers/apiRoutes/team.js
  models/Project.js
  package.json
Labels: Back End, Front End

#64 Socket.io integration
  client/package.json
  client/src/App.js
  client/src/components/AddColumn.js
  client/src/components/CardComponent.js
  client/src/components/DropMenu.js
  client/src/components/Homeview.js
  client/src/components/Navbar.js
  client/src/components/ProjectCard.js
  client/src/components/drawerviews/ColumnDrawerView.js
  client/src/components/modals/LabelModal.js
  client/src/components/modals/ProjectModal.js
  client/src/components/modals/TaskModal.js
  client/src/styles/style.css
  config/config.json
  controllers/apiRoutes/columns.js
  controllers/apiRoutes/label.js
  controllers/apiRoutes/task.js
  package.json
  server.js
Labels: Back End, Front End

#69 68 settings view
  client/package.json
  client/public/android-chrome-144x144.png
  client/public/apple-touch-icon.png
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/public/mstile-150x150.png
  client/src/App.js
  client/src/autologo.png
  client/src/components/AddProject.js
  client/src/components/Column.js
  client/src/components/DropMenu.js
  client/src/components/Homeview.js
  client/src/components/Login.js
  client/src/components/Navbar.js
  client/src/components/ProjectCard.js
  client/src/components/TeamDropItem.js
  client/src/components/TeamDropdown.js
  client/src/components/TeamMenu.js
  client/src/components/Timeline.js
  client/src/components/drawerviews/SettingsDrawerView.js
  client/src/components/modals/ProjectModal.js
  client/src/components/modals/TaskModal.js
  client/src/logo.png
  client/src/styles/style.css
  controllers/apiRoutes/label.js
  controllers/apiRoutes/project.js
  controllers/apiRoutes/task.js
  controllers/apiRoutes/team.js
  controllers/apiRoutes/user.js
  models/Task.js
  models/Team.js
Labels: Back End, Front End

#72 Added markdown support for task description
  client/package.json
  client/src/components/CardComponent.js
  config/config.json
Labels: Front End, enhancement
