Repository TheAutobanApp/Autoban, pull requests merged in 2020-07, with the labels that each got.

#6 Cleaned up the extra
  client/src/App.js
  client/src/components/Form/index.js
  client/src/components/Form/style.css
  config/config.json
  controllers/api/burger.js
  controllers/api/index.js
  controllers/index.js
  models/burger.js
  models/customer.js
Labels: Back End, Front End, MVP

#9 Added draw.io documentation to readme
  README.md
  documentation/autoban-compLayout.jpg
  documentation/autoban-schema.jpg
Labels: documentation

#15 Drawer component
  client/.gitignore
  client/package.json
  client/src/App.js
  client/src/components/Navbar.js
  client/src/components/OptionsDrawer.js
  client/src/index.js
  server.js
Labels: Front End

#19 Created column component
  .vscode/settings.json
  client/src/App.js
  client/src/components/CardComponent.js
  client/src/components/Column.js
  client/src/components/Navbar.js
  client/src/components/ProjectView.js
  client/src/index.js
  client/src/styles/style.css
  config/config.json
  package.json
Labels: Front End, MVP

#22 Stylin'
  client/public/index.html
  client/src/App.js
  client/src/autologo.png
  client/src/components/CardComponent.js
  client/src/components/Column.js
  client/src/components/Navbar.js
  client/src/components/OptionsDrawer.js
  client/src/styles/style.css
Labels: Front End, MVP

#23 updated the navbar
  client/src/components/Navbar.js
  client/src/components/TeamDropdown.js
  client/src/styles/style.css
  package.json
Labels: Front End, MVP

#26 Created dropdown component for card and column options
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/CardComponent.js
  client/src/components/Column.js
  client/src/components/DropMenu.js
  client/src/components/Navbar.js
  client/src/styles/style.css
  package.json
Labels: Front End, MVP
